In [54]:
from tensorflow.keras.models import load_model
import pickle
import numpy as np
import pandas as pd

In [55]:
## Loading the model, Ohe_encoder, label_gender and Scalar Pickle files
model=load_model('model_1.h5')

with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender=pickle.load(file)
with open('ohe_geo_encoder.pkl','rb') as file:
    ohe_geo_encoder=pickle.load(file)
with open('scaler.pkl','rb') as file:
    scaler=pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [56]:
#Example data
input_data={
    'CreditScore':650,
    'Geography':'France',
    'Gender':'Female',
    'Age':45,
    'Tenure':1,
    'Balance':70000,
    'NumOfProducts':2,
    'HasCrCard':5,
    'IsActiveMember':1,
    'EstimatedSalary':30000
}

In [57]:
geo_encoded=ohe_geo_encoder.transform([[input_data['Geography']]]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=ohe_geo_encoder.get_feature_names_out(['Geography']))
geo_encoded_df

c:\Users\Hari Vallabh\GenAI\Deep Learning\GenAI\main_venv\Lib\site-packages\sklearn\utils\validation.py:2830: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [58]:
input_data=pd.DataFrame([input_data])
input_data=pd.concat([input_data.drop('Geography',axis=1),geo_encoded_df],axis=1)
input_data['Gender']=label_encoder_gender.transform(input_data['Gender'])
input_data

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          650       0  ...                0.0              0.0

[1 rows x 12 columns]

In [59]:
#scaling
input_scaled=scaler.transform(input_data)
input_scaled

array([[-8.23973682e-04, -1.08729708e+00,  5.74572784e-01,
        -1.39048495e+00, -1.02329642e-01,  8.07123504e-01,
         9.40654444e+00,  9.79215941e-01, -1.21153111e+00,
         1.00275379e+00, -5.82161605e-01, -5.74655953e-01]])

In [60]:
predicted=model.predict(input_scaled)
predicted

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

array([[0.6179161]], dtype=float32)

In [61]:
if predicted>0.5:
    print(f"They'll be likely to leave the job since the probability is {predicted*100}")
else:
    print(f'No, they will continue working ')

They'll be likely to leave the job since the probability is [[61.79161]]