# Data Preprocessing and Cleaning

In [21]:
import pandas as pd
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [22]:
data = data.drop(
    columns=['RowNumber', 'CustomerId', 'Surname'],
    errors='ignore'
)

data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [23]:
#Encode all the Labeled data to categorical data like gender-> use label encoder
from sklearn.preprocessing import LabelEncoder
label_encoder_gender=LabelEncoder()

In [24]:
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [25]:
#since there are different geographical names -> better to use OHE
from sklearn.preprocessing import OneHotEncoder
ohe_geo_encoder=OneHotEncoder()
geo=ohe_geo_encoder.fit_transform(data[['Geography']])
geo

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [26]:
ohe_geo_encoder.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [27]:
geo_encoded_df=pd.DataFrame(geo.toarray(),columns=ohe_geo_encoder.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [28]:
data=pd.concat([data.drop('Geography', axis=1),geo_encoded_df],axis=1)

In [29]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [30]:
#Saving the encoded valuses in the pickle files, so that they are saved and we can work on other part of the memory and dataset.
# Gender -> Label Encoder
#  Geography -> OHE
import pickle
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

In [31]:
with open('ohe_geo_encoder.pkl','wb') as file:
    pickle.dump(ohe_geo_encoder,file)

In [32]:
#Divide teh dataset into Independent and Depedent Feature
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [33]:
#X-independent, y-depedent
X=data.drop(['Exited'],axis=1)
y=data['Exited']

In [34]:
X.head(2)

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0.0,0.0,1.0

In [35]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=6)

In [36]:
#scaling the data
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [37]:
X_train

array([[-1.50603574, -1.08729708, -1.32582299, ..., -0.99725377,
         1.71773609, -0.57465595],
       [ 1.03725311,  0.91971184,  0.09947384, ..., -0.99725377,
         1.71773609, -0.57465595],
       [-0.74823947,  0.91971184, -0.47064489, ...,  1.00275379,
        -0.5821616 , -0.57465595],
       ...,
       [-0.86242795, -1.08729708, -1.51586256, ...,  1.00275379,
        -0.5821616 , -0.57465595],
       [ 0.27945684, -1.08729708, -1.2308032 , ..., -0.99725377,
         1.71773609, -0.57465595],
       [-0.04234706,  0.91971184,  1.04967173, ..., -0.99725377,
         1.71773609, -0.57465595]], shape=(8000, 12))

In [38]:
#we'll save this Scalar data in the pickle file
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

# ANN implementation

In [39]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [51]:
model=Sequential([
    Dense(80,activation='relu',input_shape=(X_train.shape[1],)),#HL-1 - Connected to input layer
    Dense(40,activation='relu'),#HL-2
    Dense(1,activation='relu')#output layer
]
)

c:\Users\Hari Vallabh\GenAI\Deep Learning\GenAI\main_venv\Lib\site-packages\keras\src\layers\core\dense.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [52]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 80)             │         1,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 40)             │         3,240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            41 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,321 (16.88 KB)

 Trainable params: 4,321 (16.88 KB)

 Non-trainable params: 0 (0.00 B)

In [53]:
opt=tf.keras.optimizers.Adam(learning_rate=0.001)
loss=tf.keras.losses.BinaryCrossentropy()
loss

In [54]:
#TO train the model we need to compile itfirst
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [44]:
# set the TensorBoard 
log_dir='log/fit/'+datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorlfow_callbacks=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [55]:
## setup the EarlyStopping
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=20,restore_best_weights=True)

# Model Training

In [56]:
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=60,
    callbacks=[tensorlfow_callbacks,early_stopping_callback]
)

Epoch 1/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7869 - loss: 0.8579 - val_accuracy: 0.8145 - val_loss: 0.5706
Epoch 2/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8156 - loss: 0.5105 - val_accuracy: 0.8300 - val_loss: 0.4616
Epoch 3/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8401 - loss: 0.4758 - val_accuracy: 0.8095 - val_loss: 0.4670
Epoch 4/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8256 - loss: 0.5005 - val_accuracy: 0.8450 - val_loss: 0.4262
Epoch 5/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8416 - loss: 0.4528 - val_accuracy: 0.8530 - val_loss: 0.4667
Epoch 6/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8385 - loss: 0.4436 - val_accuracy: 0.8255 - val_loss: 0.5560
Epoch 7/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8422 - loss: 0.4304 - val_accuracy: 0.8455 - val_loss: 0.5003
Epoch 8/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8461 - loss: 0.4178 - val_accuracy: 0.8485 - val_loss: 0.4471
Epoch 9/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8455 - loss: 0.4211 - val_accuracy: 0.8445 - val_loss: 0.4353
Epoch 10/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8363 - loss: 0.4517 - val_accuracy: 0.8440 - val_loss: 0.4372
Epoch 11/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8410 - loss: 0.4311 - val_accuracy: 0.7870 - val_loss: 0.4989
Epoch 12/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8424 - loss: 0.4108 - val_accuracy: 0.8540 - val_loss: 0.4410
Epoch 13/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8586 - loss: 0.3991 - val_accuracy: 0.8565 - val_loss: 0.4528
Epoch 14/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8505 - loss: 0.4055 - val_accuracy: 0.8165 - val_loss: 0.5099
Epoch 15/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8359 - loss: 0.4365 - val_accuracy: 0.8500 - val_loss: 0.4222
Epoch 16/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8590 - loss: 0.3886 - val_accuracy: 0.8480 - val_loss: 0.4402
Epoch 17/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8597 - loss: 0.3847 - val_accuracy: 0.8360 - val_loss: 0.4491
Epoch 18/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8535 - loss: 0.3770 - val_accuracy: 0.8425 - val_loss: 0.4487
Epoch 19/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8577 - loss: 0.4123 - val_accuracy: 0.8480 - val_loss: 0.4542
Epoch 20/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8602 - loss: 0.3733 - val_accuracy: 0.8525 - val_loss: 0.4158
Epoch 21/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8624 - loss: 0.3619 - val_accuracy: 0.8525 - val_loss: 0.4210
Epoch 22/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8605 - loss: 0.3519 - val_accuracy: 0.8515 - val_loss: 0.4353
Epoch 23/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8641 - loss: 0.3453 - val_accuracy: 0.8515 - val_loss: 0.4412
Epoch 24/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8640 - loss: 0.3421 - val_accuracy: 0.8515 - val_loss: 0.4472
Epoch 25/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8650 - loss: 0.3395 - val_accuracy: 0.8520 - val_loss: 0.4486
Epoch 26/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8656 - loss: 0.3374 - val_accuracy: 0.8515 - val_loss: 0.4590
Epoch 27/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8661 - loss: 0.3353 - val_accuracy: 0.8520 - val_loss: 0.4662
Epoch 28/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8666 - loss: 0.3331 - val_accuracy: 0.8505 - val_loss: 0.4734
Epoch 29/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8685 - loss: 0.3314 - val_accuracy: 0.8495 - val_loss: 0.4799
Epoch 30/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8673 - loss: 0.3296 - val_accuracy: 0.8490 - val_loss: 0.4927
Epoch 31/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8680 - loss: 0.3278 - val_accuracy: 0.8525 - val_loss: 0.5102
Epoch 32/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8685 - loss: 0.3291 - val_accuracy: 0.8530 - val_loss: 0.5249
Epoch 33/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8705 - loss: 0.3254 - val_accuracy: 0.8510 - val_loss: 0.5200
Epoch 34/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8701 - loss: 0.3207 - val_accuracy: 0.8500 - val_loss: 0.5303
Epoch 35/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8696 - loss: 0.3188 - val_accuracy: 0.8500 - val_loss: 0.5365
Epoch 36/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8699 - loss: 0.3164 - val_accuracy: 0.8540 - val_loss: 0.5484
Epoch 37/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8696 - loss: 0.3140 - val_accuracy: 0.8540 - val_loss: 0.5508
Epoch 38/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8696 - loss: 0.3114 - val_accuracy: 0.8555 - val_loss: 0.5683
Epoch 39/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8704 - loss: 0.3104 - val_accuracy: 0.8525 - val_loss: 0.5695
Epoch 40/60
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8699 - loss: 0.3084 - val_accuracy: 0.8560 - val_loss: 0.5843

In [57]:
model.save('model_1.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [48]:
#Load TB extension
%load_ext tensorboard